# Generated by Django 3.1.3 on 2023-01-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230110_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='content',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.FloatField(),
        ),
    ]
