# Generated by Django 3.1.3 on 2023-01-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230115_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='question_text',
        ),
    ]
