# Generated by Django 3.1.3 on 2023-01-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_auto_20230115_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
    ]
